server:
  port: 8080

spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin123}
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: ${CONSUMER_PREFETCH:50}

ship:
  queue: ${SHIP_QUEUE:ship-order}

consumer:
  concurrency: ${CONSUMER_CONCURRENCY:8}
  max-concurrency: ${CONSUMER_MAX_CONCURRENCY:32}
  prefetch: ${CONSUMER_PREFETCH:50}
