server.port=8080
spring.application.name=bad-product-service

server.tomcat.threads.max=400
server.tomcat.threads.min-spare=50
server.tomcat.accept-count=200
server.tomcat.connection-timeout=30000

logging.level.root=INFO
logging.level.com.cs6650.productservice=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n