server:
  port: 8080

cca:
  base-url: http://cs6650-assignment03-alb-76159262.us-west-2.elb.amazonaws.com

ship:
  queue: ship-order

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin123
    publisher-confirm-type: correlated
    publisher-returns: true
