/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.swagger.client.ApiClient;
/**
 * CreateShoppingCart201Response
 */
@JsonPropertyOrder({
  CreateShoppingCart201Response.JSON_PROPERTY_SHOPPING_CART_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-30T20:20:26.525204-08:00[America/Los_Angeles]", comments = "Generator version: 7.19.0")
public class CreateShoppingCart201Response {
  public static final String JSON_PROPERTY_SHOPPING_CART_ID = "shopping_cart_id";
  @javax.annotation.Nullable
  private Integer shoppingCartId;

  public CreateShoppingCart201Response() { 
  }

  public CreateShoppingCart201Response shoppingCartId(@javax.annotation.Nullable Integer shoppingCartId) {
    this.shoppingCartId = shoppingCartId;
    return this;
  }

  /**
   * Unique identifier for the created shopping cart
   * @return shoppingCartId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHOPPING_CART_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getShoppingCartId() {
    return shoppingCartId;
  }


  @JsonProperty(value = JSON_PROPERTY_SHOPPING_CART_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShoppingCartId(@javax.annotation.Nullable Integer shoppingCartId) {
    this.shoppingCartId = shoppingCartId;
  }


  /**
   * Return true if this createShoppingCart_201_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateShoppingCart201Response createShoppingCart201Response = (CreateShoppingCart201Response) o;
    return Objects.equals(this.shoppingCartId, createShoppingCart201Response.shoppingCartId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shoppingCartId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateShoppingCart201Response {\n");
    sb.append("    shoppingCartId: ").append(toIndentedString(shoppingCartId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `shopping_cart_id` to the URL query string
    if (getShoppingCartId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sshopping_cart_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getShoppingCartId()))));
    }

    return joiner.toString();
  }
}

