/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.swagger.client.ApiClient;
/**
 * ProcessPaymentRequest
 */
@JsonPropertyOrder({
  ProcessPaymentRequest.JSON_PROPERTY_CREDIT_CARD_NUMBER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-30T20:20:26.525204-08:00[America/Los_Angeles]", comments = "Generator version: 7.19.0")
public class ProcessPaymentRequest {
  public static final String JSON_PROPERTY_CREDIT_CARD_NUMBER = "credit_card_number";
  @javax.annotation.Nonnull
  private String creditCardNumber;

  public ProcessPaymentRequest() { 
  }

  public ProcessPaymentRequest creditCardNumber(@javax.annotation.Nonnull String creditCardNumber) {
    this.creditCardNumber = creditCardNumber;
    return this;
  }

  /**
   * Credit card number as string as groups of 4 digits with dashes (minus sign)
   * @return creditCardNumber
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREDIT_CARD_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCreditCardNumber() {
    return creditCardNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_CREDIT_CARD_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreditCardNumber(@javax.annotation.Nonnull String creditCardNumber) {
    this.creditCardNumber = creditCardNumber;
  }


  /**
   * Return true if this processPayment_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessPaymentRequest processPaymentRequest = (ProcessPaymentRequest) o;
    return Objects.equals(this.creditCardNumber, processPaymentRequest.creditCardNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creditCardNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessPaymentRequest {\n");
    sb.append("    creditCardNumber: ").append(toIndentedString(creditCardNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `credit_card_number` to the URL query string
    if (getCreditCardNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scredit_card_number%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreditCardNumber()))));
    }

    return joiner.toString();
  }
}

