/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.swagger.client.ApiClient;
/**
 * Product
 */
@JsonPropertyOrder({
  Product.JSON_PROPERTY_PRODUCT_ID,
  Product.JSON_PROPERTY_SKU,
  Product.JSON_PROPERTY_MANUFACTURER,
  Product.JSON_PROPERTY_CATEGORY_ID,
  Product.JSON_PROPERTY_WEIGHT,
  Product.JSON_PROPERTY_SOME_OTHER_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-30T20:20:26.525204-08:00[America/Los_Angeles]", comments = "Generator version: 7.19.0")
public class Product {
  public static final String JSON_PROPERTY_PRODUCT_ID = "product_id";
  @javax.annotation.Nonnull
  private Integer productId;

  public static final String JSON_PROPERTY_SKU = "sku";
  @javax.annotation.Nonnull
  private String sku;

  public static final String JSON_PROPERTY_MANUFACTURER = "manufacturer";
  @javax.annotation.Nonnull
  private String manufacturer;

  public static final String JSON_PROPERTY_CATEGORY_ID = "category_id";
  @javax.annotation.Nonnull
  private Integer categoryId;

  public static final String JSON_PROPERTY_WEIGHT = "weight";
  @javax.annotation.Nonnull
  private Integer weight;

  public static final String JSON_PROPERTY_SOME_OTHER_ID = "some_other_id";
  @javax.annotation.Nonnull
  private Integer someOtherId;

  public Product() { 
  }

  public Product productId(@javax.annotation.Nonnull Integer productId) {
    this.productId = productId;
    return this;
  }

  /**
   * Unique identifier for the product
   * minimum: 1
   * @return productId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getProductId() {
    return productId;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProductId(@javax.annotation.Nonnull Integer productId) {
    this.productId = productId;
  }


  public Product sku(@javax.annotation.Nonnull String sku) {
    this.sku = sku;
    return this;
  }

  /**
   * Stock Keeping Unit - unique product code. 10 characters from the set {A-Z0-9}
   * @return sku
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SKU, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSku() {
    return sku;
  }


  @JsonProperty(value = JSON_PROPERTY_SKU, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSku(@javax.annotation.Nonnull String sku) {
    this.sku = sku;
  }


  public Product manufacturer(@javax.annotation.Nonnull String manufacturer) {
    this.manufacturer = manufacturer;
    return this;
  }

  /**
   * Product manufacturer name
   * @return manufacturer
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MANUFACTURER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getManufacturer() {
    return manufacturer;
  }


  @JsonProperty(value = JSON_PROPERTY_MANUFACTURER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setManufacturer(@javax.annotation.Nonnull String manufacturer) {
    this.manufacturer = manufacturer;
  }


  public Product categoryId(@javax.annotation.Nonnull Integer categoryId) {
    this.categoryId = categoryId;
    return this;
  }

  /**
   * Product category identifier
   * minimum: 1
   * @return categoryId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CATEGORY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getCategoryId() {
    return categoryId;
  }


  @JsonProperty(value = JSON_PROPERTY_CATEGORY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCategoryId(@javax.annotation.Nonnull Integer categoryId) {
    this.categoryId = categoryId;
  }


  public Product weight(@javax.annotation.Nonnull Integer weight) {
    this.weight = weight;
    return this;
  }

  /**
   * Product weight in grams
   * minimum: 0
   * @return weight
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WEIGHT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getWeight() {
    return weight;
  }


  @JsonProperty(value = JSON_PROPERTY_WEIGHT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWeight(@javax.annotation.Nonnull Integer weight) {
    this.weight = weight;
  }


  public Product someOtherId(@javax.annotation.Nonnull Integer someOtherId) {
    this.someOtherId = someOtherId;
    return this;
  }

  /**
   * Additional identifier for product
   * minimum: 1
   * @return someOtherId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SOME_OTHER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getSomeOtherId() {
    return someOtherId;
  }


  @JsonProperty(value = JSON_PROPERTY_SOME_OTHER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSomeOtherId(@javax.annotation.Nonnull Integer someOtherId) {
    this.someOtherId = someOtherId;
  }


  /**
   * Return true if this Product object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Product product = (Product) o;
    return Objects.equals(this.productId, product.productId) &&
        Objects.equals(this.sku, product.sku) &&
        Objects.equals(this.manufacturer, product.manufacturer) &&
        Objects.equals(this.categoryId, product.categoryId) &&
        Objects.equals(this.weight, product.weight) &&
        Objects.equals(this.someOtherId, product.someOtherId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId, sku, manufacturer, categoryId, weight, someOtherId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Product {\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    someOtherId: ").append(toIndentedString(someOtherId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `product_id` to the URL query string
    if (getProductId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproduct_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProductId()))));
    }

    // add `sku` to the URL query string
    if (getSku() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssku%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSku()))));
    }

    // add `manufacturer` to the URL query string
    if (getManufacturer() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smanufacturer%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getManufacturer()))));
    }

    // add `category_id` to the URL query string
    if (getCategoryId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scategory_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCategoryId()))));
    }

    // add `weight` to the URL query string
    if (getWeight() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sweight%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWeight()))));
    }

    // add `some_other_id` to the URL query string
    if (getSomeOtherId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssome_other_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSomeOtherId()))));
    }

    return joiner.toString();
  }
}

