/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProcessPaymentRequest
 */
class ProcessPaymentRequestTest {
    private final ProcessPaymentRequest model = new ProcessPaymentRequest();

    /**
     * Model tests for ProcessPaymentRequest
     */
    @Test
    void testProcessPaymentRequest() {
        // TODO: test ProcessPaymentRequest
    }

    /**
     * Test the property 'creditCardNumber'
     */
    @Test
    void creditCardNumberTest() {
        // TODO: test creditCardNumber
    }

}
