/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Product
 */
class ProductTest {
    private final Product model = new Product();

    /**
     * Model tests for Product
     */
    @Test
    void testProduct() {
        // TODO: test Product
    }

    /**
     * Test the property 'productId'
     */
    @Test
    void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'sku'
     */
    @Test
    void skuTest() {
        // TODO: test sku
    }

    /**
     * Test the property 'manufacturer'
     */
    @Test
    void manufacturerTest() {
        // TODO: test manufacturer
    }

    /**
     * Test the property 'categoryId'
     */
    @Test
    void categoryIdTest() {
        // TODO: test categoryId
    }

    /**
     * Test the property 'weight'
     */
    @Test
    void weightTest() {
        // TODO: test weight
    }

    /**
     * Test the property 'someOtherId'
     */
    @Test
    void someOtherIdTest() {
        // TODO: test someOtherId
    }

}
