/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;

import io.swagger.client.model.AddItemsToCartRequest;
import io.swagger.client.model.CheckoutCart200Response;
import io.swagger.client.model.CheckoutCartRequest;
import io.swagger.client.model.CreateShoppingCart201Response;
import io.swagger.client.model.CreateShoppingCartRequest;
import io.swagger.client.model.Error;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-30T20:20:26.525204-08:00[America/Los_Angeles]", comments = "Generator version: 7.19.0")
public class ShoppingCartApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public ShoppingCartApi() {
    this(Configuration.getDefaultApiClient());
  }

  public ShoppingCartApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Add items to shopping cart
   * Add products with specified quantities to a shopping cart
   * @param shoppingCartId Unique identifier for the shopping cart (required)
   * @param addItemsToCartRequest  (required)
   * @throws ApiException if fails to make API call
   */
  public void addItemsToCart(@javax.annotation.Nonnull Integer shoppingCartId, @javax.annotation.Nonnull AddItemsToCartRequest addItemsToCartRequest) throws ApiException {
    addItemsToCart(shoppingCartId, addItemsToCartRequest, null);
  }

  /**
   * Add items to shopping cart
   * Add products with specified quantities to a shopping cart
   * @param shoppingCartId Unique identifier for the shopping cart (required)
   * @param addItemsToCartRequest  (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void addItemsToCart(@javax.annotation.Nonnull Integer shoppingCartId, @javax.annotation.Nonnull AddItemsToCartRequest addItemsToCartRequest, Map<String, String> headers) throws ApiException {
    addItemsToCartWithHttpInfo(shoppingCartId, addItemsToCartRequest, headers);
  }

  /**
   * Add items to shopping cart
   * Add products with specified quantities to a shopping cart
   * @param shoppingCartId Unique identifier for the shopping cart (required)
   * @param addItemsToCartRequest  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> addItemsToCartWithHttpInfo(@javax.annotation.Nonnull Integer shoppingCartId, @javax.annotation.Nonnull AddItemsToCartRequest addItemsToCartRequest) throws ApiException {
    return addItemsToCartWithHttpInfo(shoppingCartId, addItemsToCartRequest, null);
  }

  /**
   * Add items to shopping cart
   * Add products with specified quantities to a shopping cart
   * @param shoppingCartId Unique identifier for the shopping cart (required)
   * @param addItemsToCartRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> addItemsToCartWithHttpInfo(@javax.annotation.Nonnull Integer shoppingCartId, @javax.annotation.Nonnull AddItemsToCartRequest addItemsToCartRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = addItemsToCartRequestBuilder(shoppingCartId, addItemsToCartRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("addItemsToCart", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder addItemsToCartRequestBuilder(@javax.annotation.Nonnull Integer shoppingCartId, @javax.annotation.Nonnull AddItemsToCartRequest addItemsToCartRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'shoppingCartId' is set
    if (shoppingCartId == null) {
      throw new ApiException(400, "Missing the required parameter 'shoppingCartId' when calling addItemsToCart");
    }
    // verify the required parameter 'addItemsToCartRequest' is set
    if (addItemsToCartRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'addItemsToCartRequest' when calling addItemsToCart");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/shopping-carts/{shoppingCartId}/addItem"
        .replace("{shoppingCartId}", ApiClient.urlEncode(shoppingCartId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(addItemsToCartRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Checkout shopping cart
   * Process checkout for a shopping cart
   * @param shoppingCartId Unique identifier for the shopping cart (required)
   * @param checkoutCartRequest  (required)
   * @return CheckoutCart200Response
   * @throws ApiException if fails to make API call
   */
  public CheckoutCart200Response checkoutCart(@javax.annotation.Nonnull Integer shoppingCartId, @javax.annotation.Nonnull CheckoutCartRequest checkoutCartRequest) throws ApiException {
    return checkoutCart(shoppingCartId, checkoutCartRequest, null);
  }

  /**
   * Checkout shopping cart
   * Process checkout for a shopping cart
   * @param shoppingCartId Unique identifier for the shopping cart (required)
   * @param checkoutCartRequest  (required)
   * @param headers Optional headers to include in the request
   * @return CheckoutCart200Response
   * @throws ApiException if fails to make API call
   */
  public CheckoutCart200Response checkoutCart(@javax.annotation.Nonnull Integer shoppingCartId, @javax.annotation.Nonnull CheckoutCartRequest checkoutCartRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<CheckoutCart200Response> localVarResponse = checkoutCartWithHttpInfo(shoppingCartId, checkoutCartRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Checkout shopping cart
   * Process checkout for a shopping cart
   * @param shoppingCartId Unique identifier for the shopping cart (required)
   * @param checkoutCartRequest  (required)
   * @return ApiResponse&lt;CheckoutCart200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CheckoutCart200Response> checkoutCartWithHttpInfo(@javax.annotation.Nonnull Integer shoppingCartId, @javax.annotation.Nonnull CheckoutCartRequest checkoutCartRequest) throws ApiException {
    return checkoutCartWithHttpInfo(shoppingCartId, checkoutCartRequest, null);
  }

  /**
   * Checkout shopping cart
   * Process checkout for a shopping cart
   * @param shoppingCartId Unique identifier for the shopping cart (required)
   * @param checkoutCartRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CheckoutCart200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CheckoutCart200Response> checkoutCartWithHttpInfo(@javax.annotation.Nonnull Integer shoppingCartId, @javax.annotation.Nonnull CheckoutCartRequest checkoutCartRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = checkoutCartRequestBuilder(shoppingCartId, checkoutCartRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("checkoutCart", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CheckoutCart200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CheckoutCart200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CheckoutCart200Response>() {});
        

        return new ApiResponse<CheckoutCart200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder checkoutCartRequestBuilder(@javax.annotation.Nonnull Integer shoppingCartId, @javax.annotation.Nonnull CheckoutCartRequest checkoutCartRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'shoppingCartId' is set
    if (shoppingCartId == null) {
      throw new ApiException(400, "Missing the required parameter 'shoppingCartId' when calling checkoutCart");
    }
    // verify the required parameter 'checkoutCartRequest' is set
    if (checkoutCartRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'checkoutCartRequest' when calling checkoutCart");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/shopping-carts/{shoppingCartId}/checkout"
        .replace("{shoppingCartId}", ApiClient.urlEncode(shoppingCartId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(checkoutCartRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Create a new shopping cart
   * Create a new shopping cart for a customer
   * @param createShoppingCartRequest  (required)
   * @return CreateShoppingCart201Response
   * @throws ApiException if fails to make API call
   */
  public CreateShoppingCart201Response createShoppingCart(@javax.annotation.Nonnull CreateShoppingCartRequest createShoppingCartRequest) throws ApiException {
    return createShoppingCart(createShoppingCartRequest, null);
  }

  /**
   * Create a new shopping cart
   * Create a new shopping cart for a customer
   * @param createShoppingCartRequest  (required)
   * @param headers Optional headers to include in the request
   * @return CreateShoppingCart201Response
   * @throws ApiException if fails to make API call
   */
  public CreateShoppingCart201Response createShoppingCart(@javax.annotation.Nonnull CreateShoppingCartRequest createShoppingCartRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateShoppingCart201Response> localVarResponse = createShoppingCartWithHttpInfo(createShoppingCartRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Create a new shopping cart
   * Create a new shopping cart for a customer
   * @param createShoppingCartRequest  (required)
   * @return ApiResponse&lt;CreateShoppingCart201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateShoppingCart201Response> createShoppingCartWithHttpInfo(@javax.annotation.Nonnull CreateShoppingCartRequest createShoppingCartRequest) throws ApiException {
    return createShoppingCartWithHttpInfo(createShoppingCartRequest, null);
  }

  /**
   * Create a new shopping cart
   * Create a new shopping cart for a customer
   * @param createShoppingCartRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateShoppingCart201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateShoppingCart201Response> createShoppingCartWithHttpInfo(@javax.annotation.Nonnull CreateShoppingCartRequest createShoppingCartRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createShoppingCartRequestBuilder(createShoppingCartRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createShoppingCart", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateShoppingCart201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateShoppingCart201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateShoppingCart201Response>() {});
        

        return new ApiResponse<CreateShoppingCart201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createShoppingCartRequestBuilder(@javax.annotation.Nonnull CreateShoppingCartRequest createShoppingCartRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'createShoppingCartRequest' is set
    if (createShoppingCartRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'createShoppingCartRequest' when calling createShoppingCart");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/shopping-cart";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createShoppingCartRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
