/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.ProcessPaymentRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for PaymentsApi
 */
@Disabled
public class PaymentsApiTest {

    private final PaymentsApi api = new PaymentsApi();

    
    /**
     * Authorize and process credit card payment, called by shoppinCart.checkout. Internal API
     *
     * Process payment for a shopping cart using credit card information
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processPaymentTest() throws ApiException {
        ProcessPaymentRequest processPaymentRequest = null;
        
        api.processPayment(processPaymentRequest);
        
        // TODO: test validations
    }
    
}
