/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CreateProduct201Response;
import io.swagger.client.model.Error;
import io.swagger.client.model.Product;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for ProductApi
 */
@Disabled
public class ProductApiTest {

    private final ProductApi api = new ProductApi();

    
    /**
     * Create a product, with the provided details
     *
     * Create a product, with the provided details. Server creates the new product_id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createProductTest() throws ApiException {
        Product product = null;
        CreateProduct201Response response = 
        api.createProduct(product);
        
        // TODO: test validations
    }
    
    /**
     * Get product by ID
     *
     * Retrieve a product&#39;s details using its unique identifier
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProductTest() throws ApiException {
        Integer productId = null;
        Product response = 
        api.getProduct(productId);
        
        // TODO: test validations
    }
    
}
