/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AddItemsToCartRequest;
import io.swagger.client.model.CheckoutCart200Response;
import io.swagger.client.model.CheckoutCartRequest;
import io.swagger.client.model.CreateShoppingCart201Response;
import io.swagger.client.model.CreateShoppingCartRequest;
import io.swagger.client.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for ShoppingCartApi
 */
@Disabled
public class ShoppingCartApiTest {

    private final ShoppingCartApi api = new ShoppingCartApi();

    
    /**
     * Add items to shopping cart
     *
     * Add products with specified quantities to a shopping cart
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addItemsToCartTest() throws ApiException {
        Integer shoppingCartId = null;
        AddItemsToCartRequest addItemsToCartRequest = null;
        
        api.addItemsToCart(shoppingCartId, addItemsToCartRequest);
        
        // TODO: test validations
    }
    
    /**
     * Checkout shopping cart
     *
     * Process checkout for a shopping cart
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkoutCartTest() throws ApiException {
        Integer shoppingCartId = null;
        CheckoutCartRequest checkoutCartRequest = null;
        CheckoutCart200Response response = 
        api.checkoutCart(shoppingCartId, checkoutCartRequest);
        
        // TODO: test validations
    }
    
    /**
     * Create a new shopping cart
     *
     * Create a new shopping cart for a customer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createShoppingCartTest() throws ApiException {
        CreateShoppingCartRequest createShoppingCartRequest = null;
        CreateShoppingCart201Response response = 
        api.createShoppingCart(createShoppingCartRequest);
        
        // TODO: test validations
    }
    
}
